// <auto-generated />
namespace Fikri_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addmodelemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmodelemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202007070129299_addmodelemployee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
